# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SED.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from test import Ui_MainWindow 

class Ui_Dialog_SED(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(864, 532)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(380, 470, 93, 28))
        font = QtGui.QFont()
        font.setFamily("隶书")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 140, 351, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.jiancejieguo = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.jiancejieguo.setObjectName("jiancejieguo")
        self.verticalLayout.addWidget(self.jiancejieguo)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 30, 347, 90))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.biaoti = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.biaoti.setFont(font)
        self.biaoti.setAlignment(QtCore.Qt.AlignCenter)
        self.biaoti.setObjectName("biaoti")
        self.verticalLayout_2.addWidget(self.biaoti)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.xuhao = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.xuhao.setObjectName("xuhao")
        self.horizontalLayout.addWidget(self.xuhao)
        self.jiance = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.jiance.setObjectName("jiance")
        self.horizontalLayout.addWidget(self.jiance)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(440, 140, 351, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.cankaojieguo = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        self.cankaojieguo.setObjectName("cankaojieguo")
        self.verticalLayout_3.addWidget(self.cankaojieguo)

        #self.setStyleSheet('''QWidget{background-color:rgb(245, 245, 245);}''')

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.jiance.clicked.connect(self.look)#显示检测结果


    '''def popWindow(self):
        from test import Ui_MainWindow 
        self.form2 = QtWidgets.QMainWindow() 
        self.ui2 = Ui_MainWindow()
        self.ui2.setupUi(self.form2)
        self.form2.show()'''

    def Valuechange(self):#序号数值改变
        f_i = open("sed_input.txt", "r")
        f_o = open("sed_output.txt", "r")


        f_i_line = f_i.readline()
        f_o_line = f_o.readline()  # 遍历第一行内容

        i = self.xuhao.value()  # 输入序号
        j = 0

        tep = f_o_line[16:28]  # 存储目标编号
        list_i = []  # sed参考
        list_o = []  # sed输出

        while f_o_line:
            if (f_o_line[16:28] != tep):
                j = j + 1
                if (j == (i + 1)):
                    break
                list_o = []
                tep = f_o_line[16:28]
            list_o.append(f_o_line)
            f_o_line = f_o.readline()
        while f_i_line:
            if (f_i_line[16:28] == tep):
                list_i.append(f_i_line)
            f_i_line = f_i.readline()
        list_i_ok = []
        list_o_ok = []
        for line in list_i:
            k = 0
            for i in line:
                if (i == "\t"):
                    k = k + 1
                    if (k != 1):
                        i = " "
                if ((k >= 1) and (i != "\t")):
                    list_i_ok.append(i)
        for line in list_o:
            k = 0
            for i in line:
                if (i == "\t"):
                    k = k + 1
                    if (k != 1):
                        i = " "
                if ((k >= 1) and (i != "\t")):
                    list_o_ok.append(i)
        return list_i_ok,list_o_ok
        #序号数值self.xuhao.value()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "返回"))
        self.label_5.setText(_translate("Dialog", "检测结果"))
        self.biaoti.setText(_translate("Dialog", "声音事件检测"))
        self.label.setText(_translate("Dialog", "测试音频序号"))
        self.jiance.setText(_translate("Dialog", "检测"))
        self.label_6.setText(_translate("Dialog", "参考结果"))

    def look(self):
        list_i,list_o=self.Valuechange()
        a = ''.join(list_o)
        b = ''.join(list_i)
        self.jiancejieguo.setText(a)
        self.cankaojieguo.setText(b)
        #print(list_i)
        #print(list_o)

'''import sys
class MyWindow(QtWidgets.QMainWindow, Ui_Dialog_SED):
    def __init__(self):
        super(MyWindow, self).__init__()
        self.setupUi(self)
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    mywindow = MyWindow()
    mywindow.show()
    sys.exit(app.exec_())'''

